version: "3.8"

services:
  nginx:
    container_name: "nginx-router"
    env_file:
      - .env
    build:
      args:
        SERVER_IP: ${SERVER_IP}
        SSL_FULLCHAIN: ${SSL_FULLCHAIN}
        SSL_PRIVKEY: ${SSL_PRIVKEY}
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    volumes:
      - "capitals-app:/var/www/html/public"
      - /etc/letsencrypt/live:/etc/certs
    networks:
      - backend-flags
    ports:
      - "80:80"
      - "443:443"
networks:
  backend-flags:
    external: true
volumes:
  capitals-app:
    external: true